/**
 * Created by dionis on 8/10/2016.
 */
app.config(function($translateProvider) {
    $translateProvider.translations('en', {
            HEADLINE: 'Hello there, This is my awesome app!',
            INTRO_TEXT: 'And it has i18n support!',
            BUTTON_TEXT_EN: 'english',
            BUTTON_TEXT_DE: 'german',
            CLOSE:"close",
            LEGAL_MENTIONS:"Legal Mentions",
            INFORMACION_GENERAL:"General informations",
            MANAGER:"Manager",
            EMAIL_LABEL:"Email",
            INFORMACION_EDITOR:"Editor informations",
            CARD_CSV:"Csv",
            CARD_NUMBER:"Card number (*)",
            CARD_DATE:"Expiration date(*)",
            DATE_PLACEHOLDER : "12/06/2016",
            CARD_NUMBER:"Card number (*)",
            EXPIRATION_DATE:"Expiration date(*)",
            CARDNUMBER_REQUIRED:"Card number is required.",
            CARDNUMBER_ERROR:"You sould provide digit.",
            FILTER_BY:"Filter results :",
            PRICE:"Price",
            DATE_BUTTOM:"Date",
            VIEW_MAP:"View Map",
            ADVACED_SEARCH:"Advanced Search",
            INIT_DATE:"Start",
            END_DATE:"End",
            FORMATION_CENTER:"Formation Center",
            OTHER_DATA:"More info",
            FORMATION_DATE:"Date",
            FORMATION_DATA:"Formation's info",
            FORMATION_ADDRESS:"Address",
            BUTTON_RESERVER:"Reserve",
            CITY:"City",
            SEARCH_IN_MAP:"Search in map",
            ITEMS_PER_PAGE: "Items per page",
            FAQ_TEXT:"FAQs Questions?",
            TESTIMONY_TEXT:"Testimonies Questions?"

        })
        .translations('fr', {
            INTRO_TEXT: 'And it has i18n support!',
            BUTTON_TEXT_EN: 'anglais',
            BUTTON_TEXT_DE: 'allemand',
            CLOSE:"ferm�",
            LEGAL_MENTIONS:"mentions legals",
            INFORMACION_GENERAL:"Renseignements generaux",
            MANAGER:"G�rant",
            EMAIL_LABEL:"courriel",
            INFORMACION_EDITOR:"information de l'editeur",
            CARD_CSV:"Csv",
            CARD_NUMBER:"numero de la carte(*)",
            CARD_DATE:"Date d'expiration(*)",
            DATE_PLACEHOLDER : "12/06/2016",
            CARD_NUMBER:"numero de la carte(*)",
            EXPIRATION_DATE:"Date d'expiration(*)",
            CARDNUMBER_REQUIRED:"il faut un numero de la carte.",
            CARDNUMBER_ERROR:"vous devrais donner des numero.",
            FILTER_BY:"les resultats du filtre:",
            PRICE:"prix",
            DATE_BUTTOM:"Date",
            VIEW_MAP:"vue du map",
            ADVACED_SEARCH:"recherche avance�",
            INIT_DATE:"debut",
            END_DATE:"fin",
            FORMATION_CENTER:"centre de formation",
            OTHER_DATA:"plus d'info",
            FORMATION_DATE:"Date",
            FORMATION_DATA:"info de formation",
            FORMATION_ADDRESS:"Adress",
            BUTTON_RESERVER:"Reserve",
            CITY:"ville",
            SEARCH_IN_MAP:"recherche dans le map",
            ITEMS_PER_PAGE: "des elements par page",
            FAQ_TEXT:"FAQs Questions?",
            TESTIMONY_TEXT:"Testimonies Questions?"
        })
    .translations('es', {
        HEADLINE: 'Hey, das ist meine großartige App!',
        INTRO_TEXT: 'Und sie untersützt mehrere Sprachen!',
        BUTTON_TEXT_EN: 'englisch',
        BUTTON_TEXT_DE: 'deutsch',
        CLOSE:"cerrar",
        LEGAL_MENTIONS:"Informacion legal",
        INFORMACION_GENERAL:"Informaciónes generales",
        MANAGER:"Gerente ",
        EMAIL_LABEL:"Correo",
        INFORMACION_EDITOR:"Informaciónes del editor",
        CARD_CSV:"Csv",
        CARD_NUMBER:"Card number (*)",
        CARD_DATE:"Expiration date(*)",
        DATE_PLACEHOLDER : "12/06/2016",
        CARD_NUMBER:"Card number (*)",
        EXPIRATION_DATE:"Expiration date(*)",
        CARDNUMBER_REQUIRED:"Card number is required.",
        CARDNUMBER_ERROR:"You sould provide digit.",
        FILTER_BY:"Filter results :",
        PRICE:"Price",
        DATE_BUTTOM:"Date",
        VIEW_MAP:"View Map",
        ADVACED_SEARCH:"Advanced Search",
        INIT_DATE:"Inicial",
        END_DATE:"Final",
        OTHER_DATA:"More info",
        FORMATION_DATE:"Date",
        FORMATION_DATA:"Formation's info",
        FORMATION_ADDRESS:"Address",
        BUTTON_RESERVER:"Reservar",
        CITY:"City",
        SEARCH_IN_MAP:"Buscar usando el mapa",
        ITEMS_PER_PAGE: "Elementos por página",
        FAQ_TEXT:"FAQs Questions?",
        TESTIMONY_TEXT:"Testimonies Questions?"

    });;
     $translateProvider.preferredLanguage('en');
});