/**
 * Created by dionis on 8/10/2016.
 */
app.config(function($translateProvider) {
    $translateProvider.translations('en', {
            HEADLINE: 'Hello there, This is my awesome app!',
            INTRO_TEXT: 'And it has i18n support!',
            BUTTON_TEXT_EN: 'english',
            BUTTON_TEXT_DE: 'german',
            CLOSE:"close",
        ///----------
            LEGAL_MENTIONS:"Legal Mentions",
            INFORMACION_GENERAL:"General informations",
            MANAGER:"Manager",
            EMAIL_LABEL:"Email",
            INFORMACION_EDITOR:"Editor informations",
            CARD_CSV:"Csv",
            CARD_NUMBER:"Card number (*)",
            CARD_DATE:"Expiration date(*)",
            DATE_PLACEHOLDER : "12/06/2016",
            CARD_NUMBER:"Card number (*)",
            EXPIRATION_DATE:"Expiration date(*)",
            CARDNUMBER_REQUIRED:"Card number is required.",
            CARDNUMBER_ERROR:"You sould provide digit.",
            FILTER_BY:"Filter results :",
            PRICE:"Price",
            DATE_BUTTOM:"Date",
            VIEW_MAP:"View Map",
            ADVACED_SEARCH:"Advanced Search",
            INIT_DATE:"Init date",
            END_DATE:"Init date",
            FORMATION_CENTER:"Formation Center",
            OTHER_DATA:"More info",
            FORMATION_DATE:"Date",
            FORMATION_DATA:"Formation's info",
            FORMATION_ADDRESS:"Address",
            BUTTON_RESERVER:"Reserve",
            CITY:"City",
            SEARCH_IN_MAP:"Search in map"

        })
        .translations('fr', {
            HEADLINE: 'Hey, das ist meine großartige App!',
            INTRO_TEXT: 'Und sie untersützt mehrere Sprachen!',
            BUTTON_TEXT_EN: 'englisch',
            BUTTON_TEXT_DE: 'deutsch',
            CLOSE:"fermer",
 ///--------------------------------------------------
            LEGAL_MENTIONS:"Mentions légales",
            INFORMACION_GENERAL:"Informations générals",
            MANAGER:"Gérant ",
            EMAIL_LABEL:"Courriel",
            INFORMACION_EDITOR:"Informations de l’éditeur",
            CARD_CSV:"Csv",
            CARD_NUMBER:"Card number (*)",
            CARD_DATE:"Expiration date(*)",
            DATE_PLACEHOLDER : "12/06/2016",
            CARD_NUMBER:"Card number (*)",
            EXPIRATION_DATE:"Expiration date(*)",
            CARDNUMBER_REQUIRED:"Card number is required.",
            CARDNUMBER_ERROR:"You sould provide digit.",
            FILTER_BY:"Filter results :",
            PRICE:"Price",
            DATE_BUTTOM:"Date",
            VIEW_MAP:"View Map",
            ADVACED_SEARCH:"Advanced Search",
            INIT_DATE:"Init date",
            END_DATE:"Init date",
            OTHER_DATA:"More info",
            FORMATION_DATE:"Date",
            FORMATION_DATA:"Formation's info",
            FORMATION_ADDRESS:"Address",
            BUTTON_RESERVER:"S'inscrire",
            CITY:"City",
            SEARCH_IN_MAP:"Search in map"
        })
    .translations('es', {
        HEADLINE: 'Hey, das ist meine großartige App!',
        INTRO_TEXT: 'Und sie untersützt mehrere Sprachen!',
        BUTTON_TEXT_EN: 'englisch',
        BUTTON_TEXT_DE: 'deutsch',
        CLOSE:"cerrar",
        ///--------------------------------------------------
        LEGAL_MENTIONS:"Informacion legal",
        INFORMACION_GENERAL:"Informaciónes generales",
        MANAGER:"Gerente ",
        EMAIL_LABEL:"Correo",
        INFORMACION_EDITOR:"Informaciónes del editor",
        CARD_CSV:"Csv",
        CARD_NUMBER:"Card number (*)",
        CARD_DATE:"Expiration date(*)",
        DATE_PLACEHOLDER : "12/06/2016",
        CARD_NUMBER:"Card number (*)",
        EXPIRATION_DATE:"Expiration date(*)",
        CARDNUMBER_REQUIRED:"Card number is required.",
        CARDNUMBER_ERROR:"You sould provide digit.",
        FILTER_BY:"Filter results :",
        PRICE:"Price",
        DATE_BUTTOM:"Date",
        VIEW_MAP:"View Map",
        ADVACED_SEARCH:"Advanced Search",
        INIT_DATE:"Init date",
        END_DATE:"Init date",
        OTHER_DATA:"More info",
        FORMATION_DATE:"Date",
        FORMATION_DATA:"Formation's info",
        FORMATION_ADDRESS:"Address",
        BUTTON_RESERVER:"Reservar",
        CITY:"City",
        SEARCH_IN_MAP:"Buscar usando el mapa"

    });;
     $translateProvider.preferredLanguage('en');
});