/**
 * Created by Admin on 04/09/2016.
 */

app.config(function ($translateProvider) {
    $translateProvider.translations('en', {
            HEADLINE: 'Hello there, This is my awesome app!',
            INTRO_TEXT: 'And it has i18n support!',
            BUTTON_TEXT_EN: 'english',
            BUTTON_TEXT_DE: 'german',
            CLOSE: "close",
            CITY: "City",
            CITY_ERROR: "City invalid",
            ADDRESS: "Address",
            ADDRESS_ERROR: "Addres invalid",
            ZIPCODE: "Zipcode",
            ZIPCODE_ERROR: "Zipcode incorrect",
            AGREMENTNAME: "Jhon",
            AGREMENTNAME_ERROR: "Name incorrect",
            AGREMENTNUMBER: "55555",
            AGREMENTNUMBER_ERROR: "Number incorrect",
            SAVE_BUTTON: "Save",
            CITY_ZIPCODE: "City/ Zipcode",
            CITY_ZIPCODE_ERROR: "Value incorrect",
            NAME: "Name",
            NAME_ERROR: "Invalid name format. You should provide between 2 and 40  characters.",
            INSERT_NAME: "Insert user´s name",
            NUMBER_TEXT: "Number",
            NOT_LOCATION_PLACE: "Not exist place location",
            LABEL_MAP: "Places in map",
            NEW_PLACE: "Add place",
            ADVANCED_SEARCH: "Advanced search",
            VIEW_MAP: "View Map",
            DELETE: "Delete",
            EDIT: "Edit",
            ACCEPT: "OK",
            CLOSE: "CLOSE",
            CANCEL: "CANCELAR",
            EDIT_PLACE: "Edit",
            //------
            LOGOUT: "LOGOUT",
            LOGOUT_USER: "Logout user",
            GEOSEARCH: "Geosearch",
            LANGUAGE: "Language",
            USER_TOOLTIP: "User´s name",
            FORMATION_TOOLTIP: "Formation´s size",

            CUSTOMER_TOOLTIP: "Customer´s size",
            GEOSEARCH_TOOLTIP: "View maps",
            LANGUAGE_TOOLTIP: "Change site languages",
            FORMATION_CENTER_TEXT: "Formation center´s name",
            ADMIN_PAGE_HEAD: "Admin places",
            ADMIN_PAGE_HEAD_DESCRIPTION: "In this window you can admin formation center's places.",
            SHOW_ALL_BUTTON: "View places",
            ADMIN_PAGE_BILL_HEAD: "Admin bills",
            ADMIN_PAGE_BILL_HEAD_DESCRIPTION: "In this window you can admin formation center's bills.",
            CARD_CSV: "Csv",
            CARD_NUMBER: "Card number (*)",
            CARD_DATE: "Expiration date(*)",
            AMOUNT: "Amount",
            AMOUNT_ERROR: "Amount invalid",
            CARD_TYPE: "Card type",
            ADMIN_PAGE_ALERT_HEAD: "Admin alerts",
            ADMIN_PAGE_ALERT_HEAD_DESCRIPTION: "In this window you can admin formation center's alerts.",
            TEXT: "Text",
            TEXT_ERROR: "Text invalid",

            //---- Piterson -------------
            REQUIRED_FIELD: "Required field",
            USERNAME: "Username",
            PASSWORD: "Password",
            INSERT_PASSWORD: "Insert password",
            REMEMBER_ME: "Remember me",
            FORGOT_PASSWORD: "Forgot Password?",
            LOGIN: "Login",
            MAIN: "Main",
            ACTIVATED: "Activated",
            CREATE: "Create",
            GO_BACK: "Go back",
            INVALID_USERNAME: "Invalid username",
            PASSWORD_MIN: "4 character minimum",
            CREATE_CREDENTIAL: "Create credential",
            UPDATE_CREDENTIAL: "Update credential",
            UPDATE: "Update",
            ADMIN_CREDENTIALS: "Admin credentials",
            CREDENTIALS: "Credentials",
            ACTIONS: "Actions",
            ADMIN_FORMATIONS: "Admin Formations",
            SEARCH_FORMATIONS_IN_LIST: "Search Formations in the list",
            CREATE_FORMATION: "Create Formation",
            PRICE: "Price",
            MAX_PEOPLE: "Max. People",
            CONFIRMED: "Confirmed",
            FORMATIONS: "Formations",
            SELECT_PLACE: "Select place",
            INSERT_PRICE: "Insert price",
            ONLY_NUMBER: "Only number",
            INSERT_MAX_PEOPLE: "Insert Max. People",
            SELECT_PSYCHOLOGIST: "Select Psychologist",
            SELECT_BAFM: "Select BAFM/BAFCRI",
            INSERT_DATES: "Insert dates",
            INSERT: "Insert",
            DATES: "Dates",
            PEAK_DATE: "Peak date",
            SEARCH_ANIMATOR_IN_LIST: "Search Animators in the list",
            ADMIN_ANIMATORS: "Admin Animators",
            CREATE_ANIMATOR: "Create Animator",
            FIRST_NAME: "First Name",
            TYPE: "Type",
            PSYCHOLOGIST: "Psychologist",
            EDIT_ANIMATOR: "Edit Animator",
            NOTHING_TO_SHOW: "Nothing to show",

            //******************* ADMIN PLATFORM **********************
            WELLCOME: "Admin Platform's services",
            FORMATION_CENTERS: "Formation Centers",
            FORMATION_CENTER_ADMIN_DESCRIPTION: "In this section you will be able to manage your formation centers",
            CREATE_FORMATION_CENTER: "Create Formation Center",
            SEARCH_FORMATION_CENTERS: "Search Formation Centers",
            EMAIL: "Email",
            PHONE_NUMBER: "Phone Number",
            DEFAULT_USERNAME: "Default Username",
            INVALID_EMAIL: "Invalid email",
            PHONE_NUMBER_ERROR: "Enter 10 digits starting with '0'",
            AT_LEAST_2_CHARACTERS: "Enter at least 2 characters",
            UPDATE_FORMATION_CENTER: "Update Formation Center",

            //------------------------------------------------------------
            ITEMS_PER_PAGE: "Items per page",


        })
        .translations('fr', {
            HEADLINE: 'Hey, das ist meine großartige App!',
            INTRO_TEXT: 'Und sie untersützt mehrere Sprachen!',
            BUTTON_TEXT_EN: 'englisch',
            BUTTON_TEXT_DE: 'deutsch',
            CLOSE: "fermer",
            CITY: "Ville",
            CITY_ERROR: "Ville pas corret",
            ADDRESS: "Address",
            ADDRESS_ERROR: "Addres pas corret",
            ZIPCODE: "Zipcode",
            ZIPCODE_ERROR: "Zipcode pas corret",
            AGREMENTNAME: "Florian",
            AGREMENTNAME_ERROR: "Prenome incorrecto",
            AGREMENTNUMBER: "55555",
            AGREMENTNUMBER_ERROR: "Nombre pas correct",
            SAVE_BUTTON: "Save",
            CITY_ZIPCODE: "Ville/ Zipcode",
            CITY_ZIPCODE_ERROR: "Value pas correct",
            NAME: "Prenome",
            NAME_ERROR: "Prenome format pas correct. You should provide between 2 and 40 characters.",
            INSERT_NAME: "Ecrive le prenome",
            NUMBER_TEXT: "Nombre",
            NOT_LOCATION_PLACE: "N´est pas place location",
            LABEL_MAP: "Leux sur le map",
            NEW_PLACE: "Ajouter lieux",
            ADVANCED_SEARCH: "Researche complex",
            VIEW_MAP: "Voir map",
            DELETE: "Delete",
            EDIT: "Editer",
            ACCEPT: "D´ACCORD",
            CLOSE: "FERMER",
            CANCEL: "CANCELAR",
            EDIT_PLACE: "Edit",
            //------
            LOGOUT: "LOGOUT",
            LOGOUT_USER: "Logout user",
            GEOSEARCH: "Geolocalisation",
            LANGUAGE: "Language",
            USER_TOOLTIP: "User´s name",
            FORMATION_TOOLTIP: "Formation´s size",
            CUSTOMER_TOOLTIP: "Customer´s size",
            GEOSEARCH_TOOLTIP: "View maps",
            LANGUAGE_TOOLTIP: "Change site languages",
            FORMATION_CENTER_TEXT: "Prenome du Centre de formation ",
            ADMIN_PAGE_HEAD: "Admin places",
            ADMIN_PAGE_HEAD_DESCRIPTION: "In this window you can admin formation center places.",
            SHOW_ALL_BUTTON: "Touts Lieuxs",
            ADMIN_PAGE_BILL_HEAD: "Management bills",
            ADMIN_PAGE_BILL_HEAD_DESCRIPTION: "In this window you can admin formation center's bills.",
            CARD_CSV: "Csv",
            CARD_NUMBER: "Card number (*)",
            CARD_DATE: "Expiration date(*)",
            AMOUNT: "Nombre",
            AMOUNT_ERROR: "Nombre invalid",
            CARD_TYPE: "Card type",
            ADMIN_PAGE_ALERT_HEAD: "Admin alerts",
            ADMIN_PAGE_ALERT_HEAD_DESCRIPTION: "In this window you can admin formation center's alerts.",
            TEXT: "Text",
            TEXT_ERROR: "Text invalid",

            //---- Piterson -------------
            REQUIRED_FIELD: "Required field",
            USERNAME: "Username",
            PASSWORD: "Password",
            INSERT_PASSWORD: "Insert password",
            REMEMBER_ME: "Remember me",
            FORGOT_PASSWORD: "Forgot Password?",
            LOGIN: "Login",
            MAIN: "Main",
            ACTIVATED: "Activated",
            CREATE: "Create",
            GO_BACK: "Go back",
            INVALID_USERNAME: "Invalid username",
            PASSWORD_MIN: "4 character minimum",
            CREATE_CREDENTIAL: "Create credential",
            UPDATE_CREDENTIAL: "Update credential",
            UPDATE: "Update",
            ADMIN_CREDENTIALS: "Admin credentials",
            CREDENTIALS: "Credentials",
            ACTIONS: "Actions",
            ADMIN_FORMATIONS: "Admin Formations",
            SEARCH_FORMATIONS_IN_LIST: "Search Formations in the list",
            CREATE_FORMATION: "Create Formation",
            PRICE: "Price",
            MAX_PEOPLE: "Max. People",
            CONFIRMED: "Confirmed",
            FORMATIONS: "Formations",
            SELECT_PLACE: "Select place",
            INSERT_PRICE: "Insert price",
            ONLY_NUMBER: "Only number",
            INSERT_MAX_PEOPLE: "Insert Max. People",
            SELECT_PSYCHOLOGIST: "Select Psychologist",
            SELECT_BAFM: "Select BAFM/BAFCRI",
            INSERT_DATES: "Insert dates",
            INSERT: "Insert",
            DATES: "Dates",
            PEAK_DATE: "Peak date",
            SEARCH_ANIMATOR_IN_LIST: "Search Animators in the list",
            ADMIN_ANIMATORS: "Admin Animators",
            CREATE_ANIMATOR: "Create Animator",
            FIRST_NAME: "First Name",
            TYPE: "Type",
            PSYCHOLOGIST: "Psychologist",
            EDIT_ANIMATOR: "Edit Animator",
            NOTHING_TO_SHOW: "Nothing to show",

            //******************* ADMIN PLATFORM **********************
            WELLCOME: "Wellcome to the ADMIN PLATFORM",
            FORMATION_CENTERS: "Formation Centers",
            FORMATION_CENTER_ADMIN_DESCRIPTION: "In this section you will be able to manage your formation centers",
            CREATE_FORMATION_CENTER: "Create Formation Center",
            SEARCH_FORMATION_CENTERS: "Search Formation Centers",
            EMAIL: "Email",
            PHONE_NUMBER: "Phone Number",
            DEFAULT_USERNAME: "Default Username",
            INVALID_EMAIL: "Invalid email",
            PHONE_NUMBER_ERROR: "Enter 10 digits starting with '0'",
            AT_LEAST_2_CHARACTERS: "Enter at least 2 characters",
            UPDATE_FORMATION_CENTER: "Update Formation Center",

            //------------------------------------------------------------
            ITEMS_PER_PAGE: "Items per page",

        })
        .translations('es', {
            HEADLINE: 'Hey, das ist meine großartige App!',
            INTRO_TEXT: 'Und sie untersützt mehrere Sprachen!',
            BUTTON_TEXT_EN: 'englisch',
            BUTTON_TEXT_DE: 'deutsch',
            CLOSE: "cerrar",
            CITY: "Ciudad",
            CITY_ERROR: "Ciudad invalidad",
            ADDRESS: "Dirección",
            ADDRESS_ERROR: "Direccion incorrecta",
            ZIPCODE: "Código postal",
            ZIPCODE_ERROR: "Código postal incorrecto",
            AGREMENTNAME: "Pedro",
            AGREMENTNAME_ERROR: "Nombre incorrecto",
            AGREMENTNUMBER: "55555",
            AGREMENTNUMBER_ERROR: "Numero incorrecto",
            SAVE_BUTTON: "Guardar",
            CITY_ZIPCODE: "Ciudad/ Zipcode",
            CITY_ZIPCODE_ERROR: "Dato incorrecto",
            NAME: "Nombre",
            NAME_ERROR: "Nombre incorrecto.Usted debe insertar entre 2 a 40 caracteres.",
            INSERT_NAME: "Inserte el nombre",
            NUMBER_TEXT: "Número",
            NOT_LOCATION_PLACE: "No existe la localización",
            LABEL_MAP: "Mapa de lugares",
            NEW_PLACE: "Añadir lugar",
            ADVANCED_SEARCH: "Búsqueda avanzada",
            VIEW_MAP: "Ver mapa",
            EDIT_PLACE: "Edit Place´s attributes",
            ADD_PLACE: "Insert Place´s attributes",
            DELETE: "Eliminar",
            EDIT: "Editar",
            ACCEPT: "ACEPTAR",
            CLOSE: "CERRAR",
            CANCEL: "CANCELAR",
            EDIT_PLACE: "Edit",
            //------
            LOGOUT: "SALIR",
            LOGOUT_USER: "Deslogear",
            GEOSEARCH: "Geolocalización",
            LANGUAGE: "Language",
            USER_TOOLTIP: "User´s name",
            FORMATION_TOOLTIP: "Formation´s size",
            CUSTOMER_TOOLTIP: "Customer´s size",
            GEOSEARCH_TOOLTIP: "View maps",
            LANGUAGE_TOOLTIP: "Change site languages",
            FORMATION_CENTER_TEXT: "Nombre del centro de formación",
            ADMIN_PAGE_HEAD: "Admin places",
            ADMIN_PAGE_HEAD_DESCRIPTION: "In this window you can admin formation center places.",
            SHOW_ALL_BUTTON: "Lugares",
            ADMIN_PAGE_BILL_HEAD: "Administrar pagos",
            ADMIN_PAGE_BILL_HEAD_DESCRIPTION: "En esta ventana usted podra administrar los pagos de un Centro de Formación.",
            CARD_CSV: "Csv",
            CARD_NUMBER: "Número de tarjeta (*)",
            CARD_DATE: "Expiration date(*)",
            AMOUNT: "Nombre",
            AMOUNT_ERROR: "Nombre invalid",
            CARD_TYPE: "Tarjeta de crédito/débito",
            ADMIN_PAGE_ALERT_HEAD: "Administrar alerts",
            ADMIN_PAGE_ALERT_HEAD_DESCRIPTION: "En esta vista se podra administrar las alertas de un Centro de Formación.",
            TEXT: "Texto",
            TEXT_ERROR: "Texto invalido",

            //---- Piterson -------------
            REQUIRED_FIELD: "Campo requerido",
            USERNAME: "Usuario",
            PASSWORD: "Contraseña",
            INSERT_PASSWORD: "Inserte contraseña",
            REMEMBER_ME: "Recordarme",
            FORGOT_PASSWORD: "Olvidó su contraseña?",
            LOGIN: "Entrar",
            MAIN: "Principal",
            ACTIVATED: "Activado",
            CREATE: "Crear",
            GO_BACK: "Ir atrás",
            INVALID_USERNAME: "Usuario inválido",
            PASSWORD_MIN: "Mínimo 4 caracteres",
            CREATE_CREDENTIAL: "Crear credencial",
            UPDATE_CREDENTIAL: "Actualizar credencial",
            UPDATE: "Actualizar",
            ADMIN_CREDENTIALS: "Administrar credenciales",
            CREDENTIALS: "Credenciales",
            ACTIONS: "Acciones",
            ADMIN_FORMATIONS: "Administrar Formaciones",
            SEARCH_FORMATIONS_IN_LIST: "Buscar Formaciones en la lista",
            CREATE_FORMATION: "Crear Formación",
            PRICE: "Precio",
            MAX_PEOPLE: "Max. Personas",
            CONFIRMED: "Confirmada",
            FORMATIONS: "Formaciones",
            SELECT_PLACE: "Seleccione el lugar",
            INSERT_PRICE: "Inserte el precio",
            ONLY_NUMBER: "Solo números",
            INSERT_MAX_PEOPLE: "Inserte Cant. Max. Personas",
            SELECT_PSYCHOLOGIST: "Seleccione el Psicólogo",
            SELECT_BAFM: "Seleccione BAFM/BAFCRI",
            INSERT_DATES: "Inserte fechas",
            INSERT: "Insertar",
            DATES: "Fechas",
            PEAK_DATE: "Seleccione fecha",
            SEARCH_ANIMATOR_IN_LIST: "Buscar Animator en la lista",
            ADMIN_ANIMATORS: "Administrar Animators",
            CREATE_ANIMATOR: "Crear Animator",
            FIRST_NAME: "Apellidos",
            TYPE: "Tipo",
            PSYCHOLOGIST: "Psicólogo",
            EDIT_ANIMATOR: "Editar Animator",
            NOTHING_TO_SHOW: "Nada para mostrar",

            //******************* ADMIN PLATFORM **********************
            WELLCOME: "Bienvenidos a la PLATAFORMA DE ADMINISTRACION",
            FORMATION_CENTERS: "Centros de Formación",
            FORMATION_CENTER_ADMIN_DESCRIPTION: "En esta sección usted prodrá administrar sus Centros de Formación",
            CREATE_FORMATION_CENTER: "Crear Centro de Formación",
            SEARCH_FORMATION_CENTERS: "Buscar Centros de Formación",
            EMAIL: "Correo electrónico",
            PHONE_NUMBER: "Número telefónico",
            DEFAULT_USERNAME: "Usuario por defecto",
            INVALID_EMAIL: "Correo inválido",
            PHONE_NUMBER_ERROR: "Entre 10 dígitos comenzando por '0'",
            AT_LEAST_2_CHARACTERS: "Entre al menos 2 caracteres",
            UPDATE_FORMATION_CENTER: "Actualizar Centro de Formación",

            //------------------------------------------------------------
            ITEMS_PER_PAGE: "Items per page",

        });
    ;
    $translateProvider.preferredLanguage('en');
});
