/**
 * Created by Admin on 04/09/2016.
 */

app.config(function ($translateProvider) {
    $translateProvider.translations('en', {
            HEADLINE: 'Hello there, This is my awesome app!',
            INTRO_TEXT: 'And it has i18n support!',
            BUTTON_TEXT_EN: 'english',
            BUTTON_TEXT_DE: 'german',
            CLOSE: "close",
            CITY: "City",
            CITY_ERROR: "City invalid",
            ADDRESS: "Address",
            ADDRESS_ERROR: "Addres invalid",
            ZIPCODE: "Zipcode",
            ZIPCODE_ERROR: "Zipcode incorrect",
            AGREMENTNAME: "Jhon",
            AGREMENTNAME_ERROR: "Name incorrect",
            AGREMENTNUMBER: "55555",
            AGREMENTNUMBER_ERROR: "Number incorrect",
            SAVE_BUTTON: "Save",
            CITY_ZIPCODE: "City/ Zipcode",
            CITY_ZIPCODE_ERROR: "Value incorrect",
            NAME: "Name",
            NAME_ERROR: "Invalid name format. You should provide between 2 and 40  characters.",
            INSERT_NAME: "Insert user´s name",
            NUMBER_TEXT: "Number",
            NOT_LOCATION_PLACE: "Not exist place location",
            LABEL_MAP: "Places in map",
            NEW_PLACE: "Add place",
            ADVANCED_SEARCH: "Advanced search",
            VIEW_MAP: "View Map",
            DELETE: "Delete",
            EDIT: "Edit",
            ACCEPT: "OK",
            CLOSE: "CLOSE",
            CANCEL: "CANCEL",
            EDIT_PLACE: "Edit",
            LOGOUT: "LOGOUT",
            LOGOUT_USER: "Logout user",
            GEOSEARCH: "Geosearch",
            LANGUAGE: "Language",
            USER_TOOLTIP: "User´s name",
            FORMATION_TOOLTIP: "Formation´s size",
            CUSTOMER_TOOLTIP: "Customer´s size",
            GEOSEARCH_TOOLTIP: "View maps",
            LANGUAGE_TOOLTIP: "Change site languages",
            FORMATION_CENTER_TEXT: "Formation center´s name",
            ADMIN_PAGE_HEAD: "Admin places",
            ADMIN_PAGE_HEAD_DESCRIPTION: "In this window you can admin formation center's places.",
            SHOW_ALL_BUTTON: "View places",
            ADMIN_PAGE_BILL_HEAD: "Admin bills",
            ADMIN_PAGE_BILL_HEAD_DESCRIPTION: "In this window you can admin formation center's bills.",
            CARD_CSV: "Csv",
            CARD_NUMBER: "Card number (*)",
            CARD_DATE: "Expiration date(*)",
            AMOUNT: "Amount",
            AMOUNT_ERROR: "Amount invalid",
            CARD_TYPE: "Card type",
            ADMIN_PAGE_ALERT_HEAD: "Admin alerts",
            ADMIN_PAGE_ALERT_HEAD_DESCRIPTION: "In this window you can admin formation center's alerts.",
            TEXT: "Text",
            TEXT_ERROR: "Text invalid",
            //---- Piterson -------------
            REQUIRED_FIELD: "Required field",
            USERNAME: "Username",
            PASSWORD: "Password",
            INSERT_PASSWORD: "Insert password",
            REMEMBER_ME: "Remember me",
            FORGOT_PASSWORD: "Forgot Password?",
            LOGIN: "Login",
            MAIN: "Main",
            ACTIVATED: "Activated",
            CREATE: "Create",
            GO_BACK: "Go back",
            INVALID_USERNAME: "Invalid username",
            PASSWORD_MIN: "4 character minimum",
            CREATE_CREDENTIAL: "Create credential",
            UPDATE_CREDENTIAL: "Update credential",
            UPDATE: "Update",
            ADMIN_CREDENTIALS: "Admin credentials",
            CREDENTIALS: "Credentials",
            ACTIONS: "Actions",
            ADMIN_FORMATIONS: "Admin Formations",
            SEARCH_FORMATIONS_IN_LIST: "Search Formations in the list",
            CREATE_FORMATION: "Create Formation",
            PRICE: "Price",
            MAX_PEOPLE: "Max. People",
            CONFIRMED: "Confirmed",
            FORMATIONS: "Formations",
            SELECT_PLACE: "Select place",
            INSERT_PRICE: "Insert price",
            ONLY_NUMBER: "Only number",
            INSERT_MAX_PEOPLE: "Insert Max. People",
            SELECT_PSYCHOLOGIST: "Select Psychologist",
            SELECT_BAFM: "Select BAFM/BAFCRI",
            INSERT_DATES: "Insert dates",
            INSERT: "Insert",
            DATES: "Dates",
            PEAK_DATE: "Peak date",
            SEARCH_ANIMATOR_IN_LIST: "Search Animators in the list",
            ADMIN_ANIMATORS: "Admin Animators",
            CREATE_ANIMATOR: "Create Animator",
            FIRST_NAME: "First Name",
            TYPE: "Type",
            PSYCHOLOGIST: "Psychologist",
            EDIT_ANIMATOR: "Edit Animator",
            NOTHING_TO_SHOW: "Nothing to show",

            //******************* ADMIN PLATFORM **********************
            WELLCOME: "Admin Platform's services",
            FORMATION_CENTERS: "Formation Centers",
            FORMATION_CENTER_ADMIN_DESCRIPTION: "In this section you will be able to manage your formation centers",
            CREATE_FORMATION_CENTER: "Create Formation Center",
            SEARCH_FORMATION_CENTERS: "Search Formation Centers",
            EMAIL: "Email",
            PHONE_NUMBER: "Phone Number",
            DEFAULT_USERNAME: "Default Username",
            INVALID_EMAIL: "Invalid email",
            PHONE_NUMBER_ERROR: "Enter 10 digits starting with '0'",
            AT_LEAST_2_CHARACTERS: "Enter at least 2 characters",
            UPDATE_FORMATION_CENTER: "Update Formation Center",
            ITEMS_PER_PAGE: "Items per page",
            ERROR: "Error",
            CONFIRMATION: "Confirmation",
            INFO: "Info",
            INVALID_USERNAME_PASSWORD: "Invalid username/password combination. Please check and try again",
            ERROR_USING_AUTH_SERVICE: "Error using auth service",
            ERROR_SEARCHING_FORMATION_CENTERS: "Error searching formation centers",
            ERROR_SEARCHING_FORMATION_CENTER: "Error searching formation center",
            DELETE_FORMATION_CENTER_CONFIRMATION: "You are going to delete this formation center. Continue?",
            FORMATION_CENTER_DELETED: "Formation center deleted",
            ERROR_DELETING_FORMATION_CENTER: "Error deleting formation center",
            FORMATION_CENTER_CREATED: "Formation center created",
            ERROR_CREATING_FORMATION_CENTER: "Error creating formation center",
            ENTER_VALID_NEW_PARAMETERS: "Enter valid new parameters",
            UPDATE_FORMATION_CENTER_CONFIRMATION: "You are going to update this formation center. Continue?",
            FORMATION_CENTER_UPDATED: "Formation center updated",
            ERROR_UPDATING_FORMATION_CENTER: "Error updating formation center"

        })
        .translations('fr', {
            HEADLINE: "salut, c'est mon application großartige !",
            INTRO_TEXT: 'Und sie untersützt mehrere Sprachen!',
            BUTTON_TEXT_EN: 'anglais',
            BUTTON_TEXT_DE: 'allemand',
            CLOSE: "fermer",
            CITY: "Ville",
            CITY_ERROR: "Ville pas correcte",
            ADDRESS: "Adress",
            ADDRESS_ERROR: "Adres pas correcte",
            ZIPCODE: "code postal",
            ZIPCODE_ERROR: "code postal pas correct",
            AGREMENTNAME: "pedro",
            AGREMENTNAME_ERROR: "Prènome incorrect",
            AGREMENTNUMBER: "55555",
            AGREMENTNUMBER_ERROR: "Nombre pas correct",
            SAVE_BUTTON: "enregistrer",
            CITY_ZIPCODE: "Ville/ code postal",
            CITY_ZIPCODE_ERROR: "Valeur pas correct",
            NAME: "Prènome",
            NAME_ERROR: "Prènome pas correct. vous devez ecrivez parmi 2 et 40 caractères.",
            NUMBER_TEXT: "Nombre",
            NOT_LOCATION_PLACE: "il n'y a pas de localisation",
            LABEL_MAP: "Lieux sur le map",
            NEW_PLACE: "Ajouter lieu",
            ADVANCED_SEARCH: "recherche avancée",
            VIEW_MAP: "Voir map",
            DELETE: "eliminer",
            EDIT: "Editer",
            ACCEPT: "accepter",
            CLOSE: "FERMER",
            CANCEL: "annuler",
            EDIT_PLACE: "Editer",
            LOGOUT: "abandonner",
            LOGOUT_USER: "desconecter utilisateur",
            GEOSEARCH: "Geolocalisation",
            LANGUAGE: "Langue",
            USER_TOOLTIP: "utilisateur",
            FORMATION_TOOLTIP: "taille de la formation",
            CUSTOMER_TOOLTIP: "taille du client",
            GEOSEARCH_TOOLTIP: "voir maps",
            LANGUAGE_TOOLTIP: "Changer le site du langues",
            FORMATION_CENTER_TEXT: "Prènome du Centre de formation ",
            ADMIN_PAGE_HEAD: "gérer lieux",
            ADMIN_PAGE_HEAD_DESCRIPTION: "dans ce fenetre vous pouvez gérer les lieux du centre de formation",
            SHOW_ALL_BUTTON: "Touts Lieuxs",
            ADMIN_PAGE_BILL_HEAD: "gérer des paiement",
            ADMIN_PAGE_BILL_HEAD_DESCRIPTION: "dans ce fenetre vous pouvez gérer les paiement d'un centre de formation",
            CARD_CSV: "Csv",
            CARD_NUMBER: "nombre de la carte(*)",
            CARD_DATE: "date d'expiration(*)",
            AMOUNT: "nombre",
            AMOUNT_ERROR: "numéro incorrect",
            CARD_TYPE: "carte de crédite/débite",
            ADMIN_PAGE_ALERT_HEAD: "gérer des alertes",
            ADMIN_PAGE_ALERT_HEAD_DESCRIPTION: "dans ce fenetre vous pouvez gérer les alertes d'un centre de formation",
            TEXT: "Texte",
            TEXT_ERROR: "Text incorrect",
            REQUIRED_FIELD: "il faut un champ",
            USERNAME: "utilisateur",
            PASSWORD: "mot de passe",
            INSERT_PASSWORD: "ecrivez mot de passe",
            REMEMBER_ME: "rappeller moi",
            FORGOT_PASSWORD: "mot de passe oublié?",
            LOGIN: "accepter",
            MAIN: "principal",
            ACTIVATED: "activé",
            CREATE: "creer",
            GO_BACK: "arrière",
            INVALID_USERNAME: "utilisateur incorrect",
            PASSWORD_MIN: "4 caractères minimum",
            CREATE_CREDENTIAL: "creer credential",
            UPDATE_CREDENTIAL: "mettre à jour la credential",
            UPDATE: "mettre à jour",
            ADMIN_CREDENTIALS: "gérer des credentials",
            CREDENTIALS: "Credentials",
            ACTIONS: "Actions",
            ADMIN_FORMATIONS: "gérer des Formations",
            SEARCH_FORMATIONS_IN_LIST: "chercher des formation dans la liste",
            CREATE_FORMATION: "creer Formation",
            PRICE: "prix",
            MAX_PEOPLE: "Maximum des personnes.",
            CONFIRMED: "Confirmé",
            FORMATIONS: "Formations",
            SELECT_PLACE: "choisissez le lieu",
            INSERT_PRICE: "ecrivez le prix",
            ONLY_NUMBER: "seulement des nombres",
            INSERT_MAX_PEOPLE: "ecrivez qantité maximum de personnes",
            SELECT_PSYCHOLOGIST: "choisissez la Psychologue",
            SELECT_BAFM: "choisissez BAFM/BAFCRI",
            INSERT_DATES: "ecrivez les dates",
            INSERT: "insèrer",
            DATES: "Dates",
            PEAK_DATE: "choisissez la date",
            SEARCH_ANIMATOR_IN_LIST: "chercher des travailleur dans la liste",
            ADMIN_ANIMATORS: "gérer de travailleurs",
            CREATE_ANIMATOR: "creer des travailleur",
            FIRST_NAME: "noms",
            TYPE: "Type",
            PSYCHOLOGIST: "Psychologue",
            EDIT_ANIMATOR: "Editer travailleur",
            NOTHING_TO_SHOW: "rien a montrer",
            //******************* administration de la plataforme **********************
            WELLCOME: "bienvenue à la plataforme d'administration",
            FORMATION_CENTERS: "centres de formation",
            FORMATION_CENTER_ADMIN_DESCRIPTION: "dans ce section vous serez capable de gérer votre centre de formation",
            CREATE_FORMATION_CENTER: "creer centre de formation",
            SEARCH_FORMATION_CENTERS: "chercher centre de formation",
            EMAIL: "courriel",
            PHONE_NUMBER: "numero du portable",
            DEFAULT_USERNAME: "utilisateur predeterminé",
            INVALID_EMAIL: "courriel incorrect",
            PHONE_NUMBER_ERROR: "ecrivez le 10 chiffre qui comence par '0'",
            AT_LEAST_2_CHARACTERS: "ecrivez au moins 2 caractères",
            UPDATE_FORMATION_CENTER: "mettre à jour le centre de formation",
            ITEMS_PER_PAGE: "elements par page",
            ERROR: "erreur",
            CONFIRMATION: "Confirmation",
            INFO: "Info",
            INVALID_USERNAME_PASSWORD: "combination d'utilisateur/ mot de passe incorrect. verifier et essai de nouveau s'il vous plait",
            ERROR_USING_AUTH_SERVICE: "Erreur utilisant service d'authentication",
            ERROR_SEARCHING_FORMATION_CENTERS: "erreur cherchant centres de formation",
            ERROR_SEARCHING_FORMATION_CENTER: "erreur cherchant centre de formation",
            DELETE_FORMATION_CENTER_CONFIRMATION: "vous etes sur le point d'eliminer ce centre de formation.continuer?",
            FORMATION_CENTER_DELETED: "centre de formation eliminé",
            ERROR_DELETING_FORMATION_CENTER: "erreur en eliminant centre de formation",
            FORMATION_CENTER_CREATED: "centre de formation crée",
            ERROR_CREATING_FORMATION_CENTER: "erreur en creant centre de formation",
            ENTER_VALID_NEW_PARAMETERS: "ecrivez de nouveau paramètre valable",
            UPDATE_FORMATION_CENTER_CONFIRMATION: "vous etes sur le point de mettre à jour ce centre de formation. Continuer?",
            FORMATION_CENTER_UPDATED: "centre de formation mis à jour",
            ERROR_UPDATING_FORMATION_CENTER: "erreur en mettant à jour centre de formation"

        })
        .translations('es', {
            HEADLINE: 'Hey, das ist meine großartige App!',
            INTRO_TEXT: 'Und sie untersützt mehrere Sprachen!',
            BUTTON_TEXT_EN: 'englisch',
            BUTTON_TEXT_DE: 'deutsch',
            CLOSE: "cerrar",
            CITY: "Ciudad",
            CITY_ERROR: "Ciudad invalidad",
            ADDRESS: "Dirección",
            ADDRESS_ERROR: "Direccion incorrecta",
            ZIPCODE: "Código postal",
            ZIPCODE_ERROR: "Código postal incorrecto",
            AGREMENTNAME: "Pedro",
            AGREMENTNAME_ERROR: "Nombre incorrecto",
            AGREMENTNUMBER: "55555",
            AGREMENTNUMBER_ERROR: "Numero incorrecto",
            SAVE_BUTTON: "Guardar",
            CITY_ZIPCODE: "Ciudad/ Zipcode",
            CITY_ZIPCODE_ERROR: "Dato incorrecto",
            NAME: "Nombre",
            NAME_ERROR: "Nombre incorrecto.Usted debe insertar entre 2 a 40 caracteres.",
            INSERT_NAME: "Inserte el nombre",
            NUMBER_TEXT: "Número",
            NOT_LOCATION_PLACE: "No existe la localización",
            LABEL_MAP: "Mapa de lugares",
            NEW_PLACE: "Añadir lugar",
            ADVANCED_SEARCH: "Búsqueda avanzada",
            VIEW_MAP: "Ver mapa",
            EDIT_PLACE: "Edit Place´s attributes",
            ADD_PLACE: "Insert Place´s attributes",
            DELETE: "Eliminar",
            EDIT: "Editar",
            ACCEPT: "ACEPTAR",
            CLOSE: "CERRAR",
            CANCEL: "CANCELAR",
            EDIT_PLACE: "Edit",
            LOGOUT: "SALIR",
            LOGOUT_USER: "Deslogear",
            GEOSEARCH: "Geolocalización",
            LANGUAGE: "Language",
            USER_TOOLTIP: "User´s name",
            FORMATION_TOOLTIP: "Formation´s size",
            CUSTOMER_TOOLTIP: "Customer´s size",
            GEOSEARCH_TOOLTIP: "View maps",
            LANGUAGE_TOOLTIP: "Change site languages",
            FORMATION_CENTER_TEXT: "Nombre del centro de formación",
            ADMIN_PAGE_HEAD: "Admin places",
            ADMIN_PAGE_HEAD_DESCRIPTION: "In this window you can admin formation center places.",
            SHOW_ALL_BUTTON: "Lugares",
            ADMIN_PAGE_BILL_HEAD: "Administrar pagos",
            ADMIN_PAGE_BILL_HEAD_DESCRIPTION: "En esta ventana usted podra administrar los pagos de un Centro de Formación.",
            CARD_CSV: "Csv",
            CARD_NUMBER: "Número de tarjeta (*)",
            CARD_DATE: "Expiration date(*)",
            AMOUNT: "Nombre",
            AMOUNT_ERROR: "Nombre invalid",
            CARD_TYPE: "Tarjeta de crédito/débito",
            ADMIN_PAGE_ALERT_HEAD: "Administrar alerts",
            ADMIN_PAGE_ALERT_HEAD_DESCRIPTION: "En esta vista se podra administrar las alertas de un Centro de Formación.",
            TEXT: "Texto",
            TEXT_ERROR: "Texto invalido",
            //---- Piterson -------------
            REQUIRED_FIELD: "Campo requerido",
            USERNAME: "Usuario",
            PASSWORD: "Contraseña",
            INSERT_PASSWORD: "Inserte contraseña",
            REMEMBER_ME: "Recordarme",
            FORGOT_PASSWORD: "Olvidó su contraseña?",
            LOGIN: "Entrar",
            MAIN: "Principal",
            ACTIVATED: "Activado",
            CREATE: "Crear",
            GO_BACK: "Ir atrás",
            INVALID_USERNAME: "Usuario inválido",
            PASSWORD_MIN: "Mínimo 4 caracteres",
            CREATE_CREDENTIAL: "Crear credencial",
            UPDATE_CREDENTIAL: "Actualizar credencial",
            UPDATE: "Actualizar",
            ADMIN_CREDENTIALS: "Administrar credenciales",
            CREDENTIALS: "Credenciales",
            ACTIONS: "Acciones",
            ADMIN_FORMATIONS: "Administrar Formaciones",
            SEARCH_FORMATIONS_IN_LIST: "Buscar Formaciones en la lista",
            CREATE_FORMATION: "Crear Formación",
            PRICE: "Precio",
            MAX_PEOPLE: "Max. Personas",
            CONFIRMED: "Confirmada",
            FORMATIONS: "Formaciones",
            SELECT_PLACE: "Seleccione el lugar",
            INSERT_PRICE: "Inserte el precio",
            ONLY_NUMBER: "Solo números",
            INSERT_MAX_PEOPLE: "Inserte Cant. Max. Personas",
            SELECT_PSYCHOLOGIST: "Seleccione el Psicólogo",
            SELECT_BAFM: "Seleccione BAFM/BAFCRI",
            INSERT_DATES: "Inserte fechas",
            INSERT: "Insertar",
            DATES: "Fechas",
            PEAK_DATE: "Seleccione fecha",
            SEARCH_ANIMATOR_IN_LIST: "Buscar Animator en la lista",
            ADMIN_ANIMATORS: "Administrar Animators",
            CREATE_ANIMATOR: "Crear Animator",
            FIRST_NAME: "Apellidos",
            TYPE: "Tipo",
            PSYCHOLOGIST: "Psicólogo",
            EDIT_ANIMATOR: "Editar Animator",
            NOTHING_TO_SHOW: "Nada para mostrar",

            //******************* ADMIN PLATFORM **********************
            WELLCOME: "Bienvenidos a la PLATAFORMA DE ADMINISTRACION",
            FORMATION_CENTERS: "Centros de Formación",
            FORMATION_CENTER_ADMIN_DESCRIPTION: "En esta sección usted prodrá administrar sus Centros de Formación",
            CREATE_FORMATION_CENTER: "Crear Centro de Formación",
            SEARCH_FORMATION_CENTERS: "Buscar Centros de Formación",
            EMAIL: "Correo electrónico",
            PHONE_NUMBER: "Número telefónico",
            DEFAULT_USERNAME: "Usuario por defecto",
            INVALID_EMAIL: "Correo inválido",
            PHONE_NUMBER_ERROR: "Entre 10 dígitos comenzando por '0'",
            AT_LEAST_2_CHARACTERS: "Entre al menos 2 caracteres",
            UPDATE_FORMATION_CENTER: "Actualizar Centro de Formación",
            ITEMS_PER_PAGE: "Items per page",

            ERROR: "Error",
            CONFIRMATION: "Confirmación",
            INFO: "Info",
            INVALID_USERNAME_PASSWORD: "Combinación usuario/contraseña inválida. Verifique y trate otra vez.",
            ERROR_USING_AUTH_SERVICE: "Error usando servicio de autenticación",
            ERROR_SEARCHING_FORMATION_CENTERS: "Error buscando centros de formación",
            ERROR_SEARCHING_FORMATION_CENTER: "Error buscando centro de formación",
            DELETE_FORMATION_CENTER_CONFIRMATION: "Está a punto de eliminar este centro de formación. Continuar?",
            FORMATION_CENTER_DELETED: "Centro de formación eliminado",
            ERROR_DELETING_FORMATION_CENTER: "Error eliminando centro de formación",
            FORMATION_CENTER_CREATED: "Centro de formación creado",
            ERROR_CREATING_FORMATION_CENTER: "Error creando centro de formación",
            ENTER_VALID_NEW_PARAMETERS: "Entre nuevos parámetros válidos",
            UPDATE_FORMATION_CENTER_CONFIRMATION: "Está a punto de actualizar este centro de formación. Continuar?",
            FORMATION_CENTER_UPDATED: "Centro de formación actualizado",
            ERROR_UPDATING_FORMATION_CENTER: "Error actualizando centro de formación"

        });
    ;
    $translateProvider.preferredLanguage('en');
});
